-- ======================================================================
-- Module 4 setup · StayWell Student Accommodation — MANAGER, PROPERTY, ROOM, STUDENT, LEASE, PAYMENT
-- ======================================================================
--
-- Creates the tables and loads the sample rows. Run this FIRST, in a fresh
-- database, before any of the numbered lesson files.
--
--   sqlite3 module4.db < 00-setup-staywell.sql
--
-- MySQL: run the same file after CREATE DATABASE / USE.
-- ======================================================================

CREATE TABLE MANAGER (
    MANAGER_ID   CHAR(3)      PRIMARY KEY,
    LAST_NAME    VARCHAR(15)  NOT NULL,
    FIRST_NAME   VARCHAR(15)  NOT NULL,
    PHONE        CHAR(12)
);

CREATE TABLE PROPERTY (
    PROPERTY_ID    CHAR(4)      PRIMARY KEY,
    PROPERTY_NAME  VARCHAR(30)  NOT NULL,
    STREET         VARCHAR(25),
    CITY           VARCHAR(15),
    STATE          CHAR(2),
    ZIP            CHAR(5),
    MANAGER_ID     CHAR(3),
    FOREIGN KEY (MANAGER_ID) REFERENCES MANAGER(MANAGER_ID)
);

CREATE TABLE ROOM (
    PROPERTY_ID    CHAR(4),
    ROOM_NUM       CHAR(3),
    ROOM_TYPE      VARCHAR(10),
    MONTHLY_RENT   DECIMAL(7,2),
    MAX_OCCUPANTS  SMALLINT,
    PRIMARY KEY (PROPERTY_ID, ROOM_NUM),
    FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID)
);

CREATE TABLE STUDENT (
    STUDENT_ID   CHAR(4)      PRIMARY KEY,
    LAST_NAME    VARCHAR(15)  NOT NULL,
    FIRST_NAME   VARCHAR(15)  NOT NULL,
    EMAIL        VARCHAR(30),
    HOME_STATE   CHAR(2)
);

CREATE TABLE LEASE (
    LEASE_ID       CHAR(4)   PRIMARY KEY,
    STUDENT_ID     CHAR(4),
    PROPERTY_ID    CHAR(4),
    ROOM_NUM       CHAR(3),
    START_DATE     DATE,
    END_DATE       DATE,
    MONTHLY_RENT   DECIMAL(7,2),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    FOREIGN KEY (PROPERTY_ID, ROOM_NUM) REFERENCES ROOM(PROPERTY_ID, ROOM_NUM)
);

CREATE TABLE PAYMENT (
    PAYMENT_ID     INTEGER   PRIMARY KEY,
    LEASE_ID       CHAR(4),
    PAYMENT_DATE   DATE,
    AMOUNT         DECIMAL(7,2),
    FOREIGN KEY (LEASE_ID) REFERENCES LEASE(LEASE_ID)
);

INSERT INTO MANAGER (MANAGER_ID, LAST_NAME, FIRST_NAME, PHONE) VALUES ('M01', 'Ortiz', 'Diane', '555-201-3344');
INSERT INTO MANAGER (MANAGER_ID, LAST_NAME, FIRST_NAME, PHONE) VALUES ('M02', 'Feldman', 'Bruce', '555-201-7790');
INSERT INTO PROPERTY (PROPERTY_ID, PROPERTY_NAME, STREET, CITY, STATE, ZIP, MANAGER_ID) VALUES ('P100', 'Millbrook Commons', '410 University Ave.', 'Millbrook', 'OH', '44601', 'M01');
INSERT INTO PROPERTY (PROPERTY_ID, PROPERTY_NAME, STREET, CITY, STATE, ZIP, MANAGER_ID) VALUES ('P200', 'Sycamore Court', '88 College St.', 'Millbrook', 'OH', '44601', 'M02');
INSERT INTO ROOM (PROPERTY_ID, ROOM_NUM, ROOM_TYPE, MONTHLY_RENT, MAX_OCCUPANTS) VALUES ('P100', '101', 'Single', '595.00', '1');
INSERT INTO ROOM (PROPERTY_ID, ROOM_NUM, ROOM_TYPE, MONTHLY_RENT, MAX_OCCUPANTS) VALUES ('P100', '102', 'Double', '450.00', '2');
INSERT INTO ROOM (PROPERTY_ID, ROOM_NUM, ROOM_TYPE, MONTHLY_RENT, MAX_OCCUPANTS) VALUES ('P200', '101', 'Single', '610.00', '1');
INSERT INTO ROOM (PROPERTY_ID, ROOM_NUM, ROOM_TYPE, MONTHLY_RENT, MAX_OCCUPANTS) VALUES ('P200', '201', 'Studio', '725.00', '1');
INSERT INTO ROOM (PROPERTY_ID, ROOM_NUM, ROOM_TYPE, MONTHLY_RENT, MAX_OCCUPANTS) VALUES ('P200', '202', 'Double', '465.00', '2');
INSERT INTO STUDENT (STUDENT_ID, LAST_NAME, FIRST_NAME, EMAIL, HOME_STATE) VALUES ('S001', 'Nguyen', 'Trang', 'tnguyen@example.edu', 'OH');
INSERT INTO STUDENT (STUDENT_ID, LAST_NAME, FIRST_NAME, EMAIL, HOME_STATE) VALUES ('S002', 'Carter', 'Miles', 'mcarter@example.edu', 'PA');
INSERT INTO STUDENT (STUDENT_ID, LAST_NAME, FIRST_NAME, EMAIL, HOME_STATE) VALUES ('S003', 'Ibrahim', 'Layla', 'librahim@example.edu', 'MI');
INSERT INTO STUDENT (STUDENT_ID, LAST_NAME, FIRST_NAME, EMAIL, HOME_STATE) VALUES ('S004', 'Park', 'Jason', 'jpark@example.edu', 'OH');
INSERT INTO LEASE (LEASE_ID, STUDENT_ID, PROPERTY_ID, ROOM_NUM, START_DATE, END_DATE, MONTHLY_RENT) VALUES ('L001', 'S001', 'P100', '101', '2026-08-15', '2027-05-15', '595.00');
INSERT INTO LEASE (LEASE_ID, STUDENT_ID, PROPERTY_ID, ROOM_NUM, START_DATE, END_DATE, MONTHLY_RENT) VALUES ('L002', 'S002', 'P100', '102', '2026-08-15', '2027-05-15', '450.00');
INSERT INTO LEASE (LEASE_ID, STUDENT_ID, PROPERTY_ID, ROOM_NUM, START_DATE, END_DATE, MONTHLY_RENT) VALUES ('L003', 'S003', 'P200', '201', '2026-08-15', '2027-05-15', '725.00');
INSERT INTO LEASE (LEASE_ID, STUDENT_ID, PROPERTY_ID, ROOM_NUM, START_DATE, END_DATE, MONTHLY_RENT) VALUES ('L004', 'S004', 'P200', '202', '2026-08-15', '2027-05-15', '465.00');
INSERT INTO PAYMENT (PAYMENT_ID, LEASE_ID, PAYMENT_DATE, AMOUNT) VALUES ('1', 'L001', '2026-08-01', '595.00');
INSERT INTO PAYMENT (PAYMENT_ID, LEASE_ID, PAYMENT_DATE, AMOUNT) VALUES ('2', 'L001', '2026-09-01', '595.00');
INSERT INTO PAYMENT (PAYMENT_ID, LEASE_ID, PAYMENT_DATE, AMOUNT) VALUES ('3', 'L002', '2026-08-01', '450.00');
INSERT INTO PAYMENT (PAYMENT_ID, LEASE_ID, PAYMENT_DATE, AMOUNT) VALUES ('4', 'L003', '2026-08-01', '725.00');
