-- ======================================================================
-- Module 4 setup · KimTay Pet Supplies — REP, CUSTOMER, ITEM, INVOICES, INVOICE_LINE
-- ======================================================================
--
-- Creates the tables and loads the sample rows. Run this FIRST, in a fresh
-- database, before any of the numbered lesson files.
--
--   sqlite3 module4.db < 00-setup-kimtay.sql
--
-- MySQL: run the same file after CREATE DATABASE / USE.
-- ======================================================================

CREATE TABLE REP (
    REP_NUM      CHAR(2)      PRIMARY KEY,
    LAST_NAME    VARCHAR(15)  NOT NULL,
    FIRST_NAME   VARCHAR(15)  NOT NULL,
    STREET       VARCHAR(20),
    CITY         VARCHAR(15),
    STATE        CHAR(2),
    ZIP          CHAR(5),
    COMMISSION   DECIMAL(8,2),
    RATE         DECIMAL(4,2)
);

CREATE TABLE CUSTOMER (
    CUSTOMER_NUM   CHAR(4)      PRIMARY KEY,
    CUSTOMER_NAME  VARCHAR(35)  NOT NULL,
    STREET         VARCHAR(20),
    CITY           VARCHAR(15),
    STATE          CHAR(2),
    ZIP            CHAR(5),
    BALANCE        DECIMAL(9,2),
    CREDIT_LIMIT   DECIMAL(9,2),
    REP_NUM        CHAR(2),
    FOREIGN KEY (REP_NUM) REFERENCES REP(REP_NUM)
);

CREATE TABLE ITEM (
    ITEM_ID        CHAR(4)      PRIMARY KEY,
    DESCRIPTION    VARCHAR(30)  NOT NULL,
    CATEGORY       VARCHAR(15),
    ON_HAND        SMALLINT,
    PRICE          DECIMAL(7,2),
    REORDER_LEVEL  SMALLINT
);

CREATE TABLE INVOICE (
    INVOICE_NUM    CHAR(5)   PRIMARY KEY,
    CUSTOMER_NUM   CHAR(4),
    INVOICE_DATE   DATE,
    FOREIGN KEY (CUSTOMER_NUM) REFERENCES CUSTOMER(CUSTOMER_NUM)
);

CREATE TABLE INVOICE_LINE (
    INVOICE_NUM    CHAR(5),
    ITEM_ID        CHAR(4),
    NUM_ORDERED    SMALLINT,
    QUOTED_PRICE   DECIMAL(7,2),
    PRIMARY KEY (INVOICE_NUM, ITEM_ID),
    FOREIGN KEY (INVOICE_NUM) REFERENCES INVOICE(INVOICE_NUM),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID)
);

INSERT INTO REP (REP_NUM, LAST_NAME, FIRST_NAME, STREET, CITY, STATE, ZIP, COMMISSION, RATE) VALUES ('20', 'Kaiser', 'Valerie', '624 Randall Dr.', 'Maple Grove', 'OH', '44601', '21560.00', '0.05');
INSERT INTO REP (REP_NUM, LAST_NAME, FIRST_NAME, STREET, CITY, STATE, ZIP, COMMISSION, RATE) VALUES ('35', 'Hull', 'Richard', '313 Palma Dr.', 'Maple Grove', 'OH', '44601', '39355.00', '0.07');
INSERT INTO REP (REP_NUM, LAST_NAME, FIRST_NAME, STREET, CITY, STATE, ZIP, COMMISSION, RATE) VALUES ('65', 'Perez', 'Juan', '2632 Marshall Ave.', 'Brookville', 'OH', '44403', '23764.00', '0.05');
INSERT INTO CUSTOMER (CUSTOMER_NUM, CUSTOMER_NAME, STREET, CITY, STATE, ZIP, BALANCE, CREDIT_LIMIT, REP_NUM) VALUES ('1120', 'Access Pet Center', '215 Foster Ave.', 'Maple Grove', 'OH', '44601', '3512.50', '7500.00', '20');
INSERT INTO CUSTOMER (CUSTOMER_NUM, CUSTOMER_NAME, STREET, CITY, STATE, ZIP, BALANCE, CREDIT_LIMIT, REP_NUM) VALUES ('1225', 'Downtown Aquarium & Pets', '642 Chestnut St.', 'Northfield', 'OH', '44067', '1200.00', '5000.00', '35');
INSERT INTO CUSTOMER (CUSTOMER_NUM, CUSTOMER_NAME, STREET, CITY, STATE, ZIP, BALANCE, CREDIT_LIMIT, REP_NUM) VALUES ('1310', 'Companion Care Clinic', '89 River Rd.', 'Maple Grove', 'OH', '44601', '0.00', '10000.00', '20');
INSERT INTO CUSTOMER (CUSTOMER_NUM, CUSTOMER_NAME, STREET, CITY, STATE, ZIP, BALANCE, CREDIT_LIMIT, REP_NUM) VALUES ('1420', 'Whiskers & Wags Boutique', '77 Elm St.', 'Brookville', 'OH', '44403', '4820.75', '6000.00', '65');
INSERT INTO ITEM (ITEM_ID, DESCRIPTION, CATEGORY, ON_HAND, PRICE, REORDER_LEVEL) VALUES ('AV07', 'Aviary Starter Cage', 'Habitat', '15', '64.99', '5');
INSERT INTO ITEM (ITEM_ID, DESCRIPTION, CATEGORY, ON_HAND, PRICE, REORDER_LEVEL) VALUES ('CF21', 'Grain-Free Dry Food 30lb', 'Food', '48', '42.50', '15');
INSERT INTO ITEM (ITEM_ID, DESCRIPTION, CATEGORY, ON_HAND, PRICE, REORDER_LEVEL) VALUES ('DG04', 'Nylon Dog Leash 6ft', 'Accessory', '120', '11.99', '25');
INSERT INTO ITEM (ITEM_ID, DESCRIPTION, CATEGORY, ON_HAND, PRICE, REORDER_LEVEL) VALUES ('FT88', 'Fish Tank Filter Kit', 'Habitat', '30', '27.75', '10');
INSERT INTO ITEM (ITEM_ID, DESCRIPTION, CATEGORY, ON_HAND, PRICE, REORDER_LEVEL) VALUES ('GR15', 'Small Animal Grooming Kit', 'Grooming', '22', '15.25', '8');
INSERT INTO INVOICE (INVOICE_NUM, CUSTOMER_NUM, INVOICE_DATE) VALUES ('50710', '1120', '2026-06-14');
INSERT INTO INVOICE (INVOICE_NUM, CUSTOMER_NUM, INVOICE_DATE) VALUES ('50711', '1420', '2026-06-14');
INSERT INTO INVOICE (INVOICE_NUM, CUSTOMER_NUM, INVOICE_DATE) VALUES ('50712', '1225', '2026-06-15');
INSERT INTO INVOICE_LINE (INVOICE_NUM, ITEM_ID, NUM_ORDERED, QUOTED_PRICE) VALUES ('50710', 'CF21', '3', '42.50');
INSERT INTO INVOICE_LINE (INVOICE_NUM, ITEM_ID, NUM_ORDERED, QUOTED_PRICE) VALUES ('50710', 'DG04', '2', '11.99');
INSERT INTO INVOICE_LINE (INVOICE_NUM, ITEM_ID, NUM_ORDERED, QUOTED_PRICE) VALUES ('50711', 'CF21', '2', '42.50');
INSERT INTO INVOICE_LINE (INVOICE_NUM, ITEM_ID, NUM_ORDERED, QUOTED_PRICE) VALUES ('50711', 'GR15', '1', '15.25');
INSERT INTO INVOICE_LINE (INVOICE_NUM, ITEM_ID, NUM_ORDERED, QUOTED_PRICE) VALUES ('50712', 'AV07', '1', '64.99');
INSERT INTO INVOICE_LINE (INVOICE_NUM, ITEM_ID, NUM_ORDERED, QUOTED_PRICE) VALUES ('50712', 'FT88', '2', '27.75');
